### PR TITLE
Control jails' start/stop notification

### PR DESCRIPTION
**Pull request by dnutan**

### CODE REVIEW

**Comment by stephdl** [comment]
Thank marc for the PR. Does the ban notifications are still sent, or all notifications are turned off ?

**Comment by dnutan** [comment]
Yes, ban notifications are sent.
There is a new db prop and a checkbox to disable email notifications of the jails being started or stopping.
On the UI reordered the jails in two columns.
Applied some minor (css) tweaks to the UI that hopefully will make it more responsive on tablets and smartphones.

**Comment by stephdl** [comment]
why do you want to modify sendmail-whois.local instead of sendmail-common.conf. In this action you have the message sent when the jail starts...I'm just advocating, because your idea is really interesting

**Comment by stephdl** [comment]
```
[root@NS7DEV9 ~]# cat /etc/fail2ban/action.d/sendmail-common.local
# Fail2Ban configuration file
#
# Common settings for sendmail actions
#
# Users can override the defaults in sendmail-common.local

[INCLUDES]

after = sendmail-common.local

[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = 

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban
# Values:  CMD
#
actionstop = 

# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck =

# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban =

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban =

[Init]

# Recipient mail address
#
dest = root

# Sender mail address
#
sender = fail2ban

# Sender display name
#
sendername = Fail2Ban


adding this and the notification are sent for bans, but no more for start/stop fail2ban Jails
```

**Comment by dnutan** [comment]
You're right. `sendmail-common.local` is the best place.
I found `sendmail-whois` was the one being used (triggered by `action_mw` on `jail.conf`), but missed `sendmail-common.conf` being included on each `sendmail-*` action file.

**Comment by stephdl** [comment]
would you please modify your commits to display this sendmail-common.local, probably we might just need to modify


```
[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = 

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban
# Values:  CMD
#
actionstop = 
```

it should be tested, think to modify some of your e-smith/nethgui properties too

**Comment by dnutan** [comment]
Sorry, missed changing a filename.
Should be all ready now.

**Comment by dnutan** [comment]
Good catch, don't know how the *whois* word slipped there ...pasting issue I guess

**Pull request merged**
